package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/tiancai110a/gin-blog/models"

	"github.com/fvbock/endless"

	"github.com/golang/glog"

	_ "github.com/tiancai110a/gin-blog/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/tiancai110a/gin-blog/pkg/log"
	"github.com/tiancai110a/gin-blog/pkg/setting"

	"github.com/tiancai110a/gin-blog/routers"
)

// @title blog API.v1
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v1
func main() {
	setting.Setup()
	models.Setup()
	log.Setup()

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, os.Kill)

	go func(c chan os.Signal) {
		<-c
		glog.Flush()
		os.Exit(0)
	}(c)

	endless.DefaultReadTimeOut = setting.ServerSetting.ReadTimeout
	endless.DefaultWriteTimeOut = setting.ServerSetting.WriteTimeout
	endless.DefaultMaxHeaderBytes = 1 << 20
	endPoint := fmt.Sprintf(":%d", setting.ServerSetting.HttpPort)

	server := endless.NewServer(endPoint, routers.InitRouter())
	server.BeforeBegin = func(add string) {
		glog.Infof("Actual pid is %d", syscall.Getpid())
	}

	err := server.ListenAndServe()
	if err != nil {
		glog.Info("Server err: %v", err)
	}
}
