basePath: /v1
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: blog API.v1
  version: "1.0"
paths:
  /api/v1/articles:
    post:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: tagid
        in: query
        name: tagid
        required: true
        type: string
      - description: data
        in: query
        name: data
        required: true
        type: string
      - description: title
        in: query
        name: title
        required: true
        type: string
      - description: desc
        in: query
        name: desc
        required: true
        type: string
      - description: content
        in: query
        name: content
        required: true
        type: string
      - description: createdBy
        in: query
        name: createdBy
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章
    put:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: tagid
        in: query
        name: tagid
        required: true
        type: string
      - description: data
        in: query
        name: data
        required: true
        type: string
      - description: title
        in: query
        name: title
        required: true
        type: string
      - description: desc
        in: query
        name: desc
        required: true
        type: string
      - description: content
        in: query
        name: content
        required: true
        type: string
      - description: createdBy
        in: query
        name: createdBy
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章
  /api/v1/tags:
    delete:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改文章标签
    get:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章标签
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
swagger: "2.0"
